### ISSUE TITLE
[feat-FE]select plant page

### ISSUE THREAD

**Issue by Remnant1318** [SproutFarmer/SproutFarmer#10]
In GitLab by @iheeya on Sep 23, 2024, 16:45

## 📔 Description

- 작물 기반 텃밭 추천 페이지 완성!

## 🐈 Todo

- [x] 작물 선택 페이지 완성
- [x] 작물 선택 페이지 모달
- [x] 로딩 페이지
- [x] 텃밭 추천 페이지
- [x] 텃밭 추천 페이지 모달
- [x] 모달 애니메이션 추가

**Comment by Remnant1318** [comment]
In GitLab by @iheeya on Sep 23, 2024, 16:46

created branch [`feat-FE-selectfarm`](/s11-bigdata-recom-sub1/S11P21D207/-/compare/master...feat-FE-selectfarm) to address this issue

**Comment by Remnant1318** [comment]
In GitLab by @iheeya on Sep 23, 2024, 17:40

marked the checklist item **작물 선택 페이지 완성** as completed

**Comment by Remnant1318** [comment]
In GitLab by @iheeya on Sep 23, 2024, 17:40

marked the checklist item **작물 선택 페이지 모달** as completed

**Comment by Remnant1318** [comment]
In GitLab by @iheeya on Sep 23, 2024, 17:40

marked the checklist item **로딩 페이지** as completed

**Comment by Remnant1318** [comment]
In GitLab by @iheeya on Sep 24, 2024, 09:58

marked the checklist item **텃밭 추천 페이지** as completed

**Comment by Remnant1318** [comment]
In GitLab by @iheeya on Sep 24, 2024, 09:58

marked the checklist item **텃밭 추천 페이지 모달** as completed

**Comment by Remnant1318** [comment]
In GitLab by @iheeya on Sep 24, 2024, 14:35

marked the checklist item **모달 애니메이션 추가** as completed
