### ISSUE TITLE
[feat-FE]community detail page

### ISSUE THREAD

**Issue by Remnant1318** [SproutFarmer/SproutFarmer#14]
In GitLab by @iheeya on Sep 24, 2024, 15:56

## 📔 Description

- 커뮤니티 디테일 페이지 보여주기

## 🐈 Todo

- [x] 커뮤니티 디테일 페이지 헤더
- [x] 커뮤니티 디테일 페이지 바디
- [x] 커뮤니티 디테일 페이지 푸터
- [x] 좋아요 만들기

**Comment by Remnant1318** [comment]
In GitLab by @iheeya on Sep 24, 2024, 15:57

created branch [`feat-FE-communitydetailget`](/s11-bigdata-recom-sub1/S11P21D207/-/compare/master...feat-FE-communitydetailget) to address this issue

**Comment by Remnant1318** [comment]
In GitLab by @iheeya on Sep 25, 2024, 17:33

marked the checklist item **커뮤니티 디테일 페이지 바디** as completed

**Comment by Remnant1318** [comment]
In GitLab by @iheeya on Sep 25, 2024, 17:33

marked the checklist item **커뮤니티 디테일 페이지 푸터** as completed

**Comment by Remnant1318** [comment]
In GitLab by @iheeya on Sep 25, 2024, 17:33

marked the checklist item **좋아요 만들기** as completed
