### ISSUE TITLE
[feat-FE] User Survey page

### ISSUE THREAD

**Issue by Remnant1318** [SproutFarmer/SproutFarmer#15]
In GitLab by @Saipola0318 on Sep 25, 2024, 13:21

## 📔 Description

회원 가입 후 최초 설문조사 페이지

## 🐈 Todo

- [x] 설문조사 목록 출력
- [x] 체크한 목록 정렬
- [x] 없음 누르면 다 태그 취소
- [x] 제출 or skip 후 자동으로 mainpage 로 연결

**Comment by Remnant1318** [comment]
In GitLab by @Saipola0318 on Sep 25, 2024, 13:21

created branch [`feat-FE-user-survey`](/s11-bigdata-recom-sub1/S11P21D207/-/compare/master...feat-FE-user-survey) to address this issue

**Comment by Remnant1318** [comment]
In GitLab by @Saipola0318 on Sep 25, 2024, 13:35

marked the checklist item **설문조사 목록 출력** as completed

**Comment by Remnant1318** [comment]
In GitLab by @Saipola0318 on Sep 25, 2024, 13:35

marked the checklist item **체크한 목록 정렬** as completed

**Comment by Remnant1318** [comment]
In GitLab by @Saipola0318 on Sep 25, 2024, 13:35

marked the checklist item **없음 누르면 다 태그 취소** as completed

**Comment by Remnant1318** [comment]
In GitLab by @Saipola0318 on Sep 25, 2024, 14:38

marked the checklist item **제출 or skip 후 자동으로 mainpage 로 연결** as completed

**Comment by Remnant1318** [comment]
In GitLab by @Saipola0318 on Sep 25, 2024, 15:39

created branch [`15-feat-fe-user-survey-page`](/s11-bigdata-recom-sub1/S11P21D207/-/compare/master...15-feat-fe-user-survey-page) to address this issue

**Comment by Remnant1318** [comment]
In GitLab by @Saipola0318 on Sep 25, 2024, 15:43

created branch [`15-feat-fe-user-survey-page`](/s11-bigdata-recom-sub1/S11P21D207/-/compare/master...15-feat-fe-user-survey-page) to address this issue

**Comment by Remnant1318** [comment]
In GitLab by @Saipola0318 on Sep 25, 2024, 15:48

created branch [`15-feat-fe-user-survey-page-2`](/s11-bigdata-recom-sub1/S11P21D207/-/compare/master...15-feat-fe-user-survey-page-2) to address this issue
