### ISSUE TITLE
[feat-FE]community comment

### ISSUE THREAD

**Issue by Remnant1318** [SproutFarmer/SproutFarmer#18]
In GitLab by @iheeya on Sep 26, 2024, 09:15

## 📔 Description

- 커뮤니티 댓글 모달 만들기!

## 🐈 Todo

- [x] 커뮤니티 댓글 모달 만들기
- [x] 커뮤니티 댓글 출력
- [x] 커뮤니티 댓글 입력
- [x] 게시글 삭제 api 연결

**Comment by Remnant1318** [comment]
In GitLab by @iheeya on Sep 26, 2024, 09:15

created branch [`feat-FE-communitycomment`](/s11-bigdata-recom-sub1/S11P21D207/-/compare/master...feat-FE-communitycomment) to address this issue

**Comment by Remnant1318** [comment]
In GitLab by @iheeya on Sep 27, 2024, 13:34

marked the checklist item **커뮤니티 댓글 출력** as completed

**Comment by Remnant1318** [comment]
In GitLab by @iheeya on Sep 27, 2024, 13:34

marked the checklist item **커뮤니티 댓글 입력** as completed

**Comment by Remnant1318** [comment]
In GitLab by @iheeya on Sep 27, 2024, 14:29

marked the checklist item **커뮤니티 댓글 모달 만들기** as completed

**Comment by Remnant1318** [comment]
In GitLab by @iheeya on Sep 27, 2024, 14:49

marked the checklist item **게시글 삭제 api 연결** as completed
