### ISSUE TITLE
[feat-FE]add farm api

### ISSUE THREAD

**Issue by Remnant1318** [SproutFarmer/SproutFarmer#20]
In GitLab by @iheeya on Sep 26, 2024, 11:11

## 📔 Description

- 텃밭 추가 페이지 api 연결

## 🐈 Todo

- [x] 텃밭기반 작물 추천 페이지 get
- [x] 텃밭기반 작물 추천 페이지 post
- [x] 작물 기반 텃밭 추천 페이지 get
- [x] 작물 기반 텃밭 추천 페이지 post

**Comment by Remnant1318** [comment]
In GitLab by @iheeya on Sep 26, 2024, 11:11

created branch [`feat-FE-addfarmapi`](/s11-bigdata-recom-sub1/S11P21D207/-/compare/master...feat-FE-addfarmapi) to address this issue

**Comment by Remnant1318** [comment]
In GitLab by @iheeya on Sep 26, 2024, 13:57

marked the checklist item **텃밭기반 작물 추천 페이지 get** as completed

**Comment by Remnant1318** [comment]
In GitLab by @iheeya on Sep 26, 2024, 14:19

marked the checklist item **텃밭기반 작물 추천 페이지 post** as completed

**Comment by Remnant1318** [comment]
In GitLab by @iheeya on Sep 26, 2024, 15:34

marked the checklist item **작물 기반 텃밭 추천 페이지 get** as completed

**Comment by Remnant1318** [comment]
In GitLab by @iheeya on Sep 26, 2024, 16:49

marked the checklist item **작물 기반 텃밭 추천 페이지 post** as completed
