### ISSUE TITLE
[feat-FE]community search

### ISSUE THREAD

**Issue by Remnant1318** [SproutFarmer/SproutFarmer#26]
In GitLab by @iheeya on Oct 2, 2024, 15:59

## 📔 Description

- 게시글 검색 기능 만들기!

## 🐈 Todo

- [x] 검색 페이지 만들기
- [x] 검색 기능 구현(get 결과물) + 출력
- [x] 검색 기록 저장, 삭제
- [x] 태그 api 통신

**Comment by Remnant1318** [comment]
In GitLab by @iheeya on Oct 2, 2024, 16:00

created branch [`feat-FE-communitysearch`](/s11-bigdata-recom-sub1/S11P21D207/-/compare/master...feat-FE-communitysearch) to address this issue

**Comment by Remnant1318** [comment]
In GitLab by @iheeya on Oct 2, 2024, 16:24

marked the checklist item **태그 api 통신** as completed

**Comment by Remnant1318** [comment]
In GitLab by @iheeya on Oct 6, 2024, 22:40

marked the checklist item **검색 페이지 만들기** as completed

**Comment by Remnant1318** [comment]
In GitLab by @iheeya on Oct 6, 2024, 22:40

marked the checklist item **검색 기능 구현(get 결과물) + 출력** as completed

**Comment by Remnant1318** [comment]
In GitLab by @iheeya on Oct 7, 2024, 10:49

marked the checklist item **검색 기록 저장, 삭제** as completed
