### ISSUE TITLE
[feat-FE] InformationPage

### ISSUE THREAD

**Issue by Remnant1318** [SproutFarmer/SproutFarmer#28]
In GitLab by @Saipola0318 on Oct 4, 2024, 17:16

## 📔 Description

정보 페이지 구현

## 🐈 Todo

- [x] 정보 페이지 컴포넌트 구현
- [x] 정보 페이지 모달 구현
- [x] 여러 다른 페이지 디자인 수정

**Comment by Remnant1318** [comment]
In GitLab by @Saipola0318 on Oct 4, 2024, 17:23

created branch [`feat-FE-informationpage`](/s11-bigdata-recom-sub1/S11P21D207/-/compare/master...feat-FE-informationpage) to address this issue

**Comment by Remnant1318** [comment]
In GitLab by @Saipola0318 on Oct 8, 2024, 10:20

marked the checklist item **정보 페이지 컴포넌트 구현** as completed

**Comment by Remnant1318** [comment]
In GitLab by @Saipola0318 on Oct 8, 2024, 10:20

marked the checklist item **정보 페이지 모달 구현** as completed

**Comment by Remnant1318** [comment]
In GitLab by @Saipola0318 on Oct 8, 2024, 10:20

marked the checklist item **여러 다른 페이지 디자인 수정** as completed
