### ISSUE TITLE
[Feat-FE] 텃밭 추가를 위한 텃밭 선택 페이지

### ISSUE THREAD

**Issue by Remnant1318** [SproutFarmer/SproutFarmer#3]
In GitLab by @iheeya on Sep 19, 2024, 14:02

## 📔 Description
- 텃밭 추가를 누른 텃밭 선택지와 위치정보 입력 모달 제공하기!

## 🐈 Todo

- [x] 선택지 컴포넌트 만들기
- [x] 텃밭 선택 페이지 만들기
- [x] 위치 정보 모달 만들기
- [x] 다음 지도 api 연결
- [x] 작물 추천 post을 위한 데이터 만들기

**Comment by Remnant1318** [comment]
In GitLab by @iheeya on Sep 19, 2024, 14:05

created branch [`feat/3-registergarden`](/s11-bigdata-recom-sub1/S11P21D207/-/compare/master...feat%2F3-registergarden) to address this issue

**Comment by Remnant1318** [comment]
In GitLab by @iheeya on Sep 19, 2024, 15:58

marked the checklist item **선택지 컴포넌트 만들기** as completed

**Comment by Remnant1318** [comment]
In GitLab by @iheeya on Sep 20, 2024, 16:42

marked the checklist item **텃밭 선택 페이지 만들기** as completed

**Comment by Remnant1318** [comment]
In GitLab by @iheeya on Sep 20, 2024, 16:42

marked the checklist item **위치 정보 모달 만들기** as completed
