### ISSUE TITLE
[feat-FE] community images

### ISSUE THREAD

**Issue by Remnant1318** [SproutFarmer/SproutFarmer#30]
In GitLab by @iheeya on Oct 7, 2024, 16:01

## 📔 Description

- 이미지 S3 연결

## 🐈 Todo

- [x] 상세 게시글 사진 s3에서 가져오기
- [x] 상세 게시글 유저 프로필 사진 S3에서 가져오기
- [x] 게시글 메인페이지 리스트 사진 s3에서 가져오기
- [x] 게시글 검색페이지 리스트 사진 s3에서 가져오기

**Comment by Remnant1318** [comment]
In GitLab by @iheeya on Oct 7, 2024, 16:01

created branch [`feat-FE-communityrewrite`](/s11-bigdata-recom-sub1/S11P21D207/-/compare/master...feat-FE-communityrewrite) to address this issue

**Comment by Remnant1318** [comment]
In GitLab by @iheeya on Oct 7, 2024, 16:55

marked the checklist item **상세 게시글 유저 프로필 사진 S3에서 가져오기** as completed

**Comment by Remnant1318** [comment]
In GitLab by @iheeya on Oct 8, 2024, 09:26

marked the checklist item **게시글 메인페이지 리스트 사진 s3에서 가져오기** as completed

**Comment by Remnant1318** [comment]
In GitLab by @iheeya on Oct 8, 2024, 09:26

marked the checklist item **게시글 검색페이지 리스트 사진 s3에서 가져오기** as completed
