### ISSUE TITLE
[feat-FE] community article modify

### ISSUE THREAD

**Issue by Remnant1318** [SproutFarmer/SproutFarmer#32]
In GitLab by @iheeya on Oct 8, 2024, 09:55

## 📔 Description

- 작물 추천 완성
- 커뮤니티 마이페이지
- 댓글 삭제

## 🐈 Todo

- [x] 내 텃밭에서 작물 추천받아서 추가
- [x] 커뮤니티 마이 페이지
- [x] 댓글 모달 css 수정
- [x] 내 댓글 삭제

**Comment by Remnant1318** [comment]
In GitLab by @iheeya on Oct 8, 2024, 09:55

created branch [`feat-FE-articlemodify`](/s11-bigdata-recom-sub1/S11P21D207/-/compare/master...feat-FE-articlemodify) to address this issue

**Comment by Remnant1318** [comment]
In GitLab by @iheeya on Oct 8, 2024, 17:48

marked the checklist item **댓글 모달 css 수정** as completed

**Comment by Remnant1318** [comment]
In GitLab by @iheeya on Oct 8, 2024, 17:48

marked the checklist item **내 댓글 삭제** as completed
