### ISSUE TITLE
[feat-FE] article modify

### ISSUE THREAD

**Issue by Remnant1318** [SproutFarmer/SproutFarmer#35]
In GitLab by @iheeya on Oct 8, 2024, 17:59

## 📔 Description

- 내 글 수정 완성
- 댓글 이미지 연결

## 🐈 Todo

- [x] 게시글 수정 form
- [x] 게시글 수정 post
- [x] 댓글 유저 프로필 s3 연결
- [x] 커뮤니티 버튼 위치 수정
- [x] 커뮤니티 디테일 하단 버튼 위치 수정
- [x] 뒤로 가기 버튼 추가

**Comment by Remnant1318** [comment]
In GitLab by @iheeya on Oct 9, 2024, 13:44

created branch [`feat-FE-community`](/s11-bigdata-recom-sub1/S11P21D207/-/compare/master...feat-FE-community) to address this issue

**Comment by Remnant1318** [comment]
In GitLab by @iheeya on Oct 9, 2024, 14:05

marked the checklist item **커뮤니티 버튼 위치 수정** as completed

**Comment by Remnant1318** [comment]
In GitLab by @iheeya on Oct 9, 2024, 14:05

marked the checklist item **커뮤니티 디테일 하단 버튼 위치 수정** as completed

**Comment by Remnant1318** [comment]
In GitLab by @iheeya on Oct 9, 2024, 14:19

marked the checklist item **댓글 유저 프로필 s3 연결** as completed

**Comment by Remnant1318** [comment]
In GitLab by @iheeya on Oct 9, 2024, 16:13

marked the checklist item **게시글 수정 form** as completed

**Comment by Remnant1318** [comment]
In GitLab by @iheeya on Oct 10, 2024, 08:56

marked the checklist item **게시글 수정 post** as completed

**Comment by Remnant1318** [comment]
In GitLab by @iheeya on Oct 10, 2024, 10:28

marked the checklist item **뒤로 가기 버튼 추가** as completed
