### ISSUE TITLE
[feat-FE] User Sign Up Page

### ISSUE THREAD

**Issue by Remnant1318** [SproutFarmer/SproutFarmer#4]
In GitLab by @Saipola0318 on Sep 19, 2024, 16:10

## 📔 Description

회원가입 페이지 구현

## 🐈 Todo

- [x] 회원가입 페이지 구현
- [x] 로그인 페이지 구현
- [x] 소셜 로그인 페이지 구현
- [x] 최초 로그인 후 설문조사 페이지 구현

**Comment by Remnant1318** [comment]
In GitLab by @Saipola0318 on Sep 19, 2024, 16:11

created branch [`4-feat-fe-user-sign-up-page`](/s11-bigdata-recom-sub1/S11P21D207/-/compare/master...4-feat-fe-user-sign-up-page) to address this issue

**Comment by Remnant1318** [comment]
In GitLab by @Saipola0318 on Sep 19, 2024, 16:29

created branch [`feat-fe-user`](/s11-bigdata-recom-sub1/S11P21D207/-/compare/master...feat-fe-user) to address this issue

**Comment by Remnant1318** [comment]
In GitLab by @Saipola0318 on Sep 25, 2024, 12:47

created branch [`4-feat-fe-user-sign-up-page`](/s11-bigdata-recom-sub1/S11P21D207/-/compare/master...4-feat-fe-user-sign-up-page) to address this issue

**Comment by Remnant1318** [comment]
In GitLab by @Saipola0318 on Sep 25, 2024, 13:13

marked the checklist item **회원가입 페이지 구현** as completed

**Comment by Remnant1318** [comment]
In GitLab by @Saipola0318 on Sep 25, 2024, 13:13

marked the checklist item **로그인 페이지 구현** as completed

**Comment by Remnant1318** [comment]
In GitLab by @Saipola0318 on Sep 25, 2024, 13:13

marked the checklist item **소셜 로그인 페이지 구현** as completed

**Comment by Remnant1318** [comment]
In GitLab by @Saipola0318 on Sep 25, 2024, 13:13

marked the checklist item **최초 로그인 후 설문조사 페이지 구현** as completed
