### ISSUE TITLE
[Feat-FE] Main Page

### ISSUE THREAD

**Issue by Remnant1318** [SproutFarmer/SproutFarmer#5]
## 📔 Description

메인 페이지 구현

## 🐈 Todo

- [ ] 메인 페이지에서 보여줄 컴포넌트들 구현
- [ ] Todo 컴포넌트
- [ ] 초보자용정보 컴포넌트
- [ ] 내 텃밭 리스트 컴포넌트( + 추가)
- [ ] 텃밭 재배 정보 컴포넌트
- [ ] 관심작물 & 텃밭 정보 컴포넌트
- [ ] 내가 키우는 작물 정보 컴포넌트
- [ ] 개인별 추천 정보 컴포넌트
- [ ] 커뮤니티 인기, 최신글 정보 컴포넌트
- [ ] 근교 주말농장 추천 컴포넌트

**Comment by Remnant1318** [comment]
created branch [`feat-FE-MainPage`](/s11-bigdata-recom-sub1/S11P21D207/-/compare/master...feat-FE-MainPage) to address this issue
